# Generated by Django 3.0.5 on 2022-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_brmuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
