# Generated by Django 3.0.5 on 2022-01-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0003_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
