# Generated by Django 3.0.5 on 2022-01-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0005_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
