# Generated by Django 3.0.5 on 2022-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='myimage'),
        ),
    ]
