# Generated by Django 3.0.5 on 2022-01-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0007_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='myimage/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='myimage/'),
        ),
        migrations.DeleteModel(
            name='bmsuser',
        ),
    ]
