# Generated by Django 4.0.1 on 2022-01-17 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0008_auto_20220117_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='myimage'),
            preserve_default=False,
        ),
    ]
